version: '3'

services:
  db:
    container_name: db
    image:
      postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    restart: always
    depends_on:
      - db
  
  redis:
    image: redis:alpine
    depends_on:
      - db

  celery:
    build: ./
    command: celery -A cpd worker -l info
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis

  celery-beat:
    build: ./
    command: celery -A cpd beat -l info
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
  
  web:
    build: ./
    command: bash -c "python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
volumes:
  local_pgdata: